### ISSUE TITLE
Error when using null actor/verb codes

### ISSUE THREAD

**Issue by ahalterman** [openeventdata/UniversalPetrarch#14]
I'm trying to run Universal Petrarch with the `null_actors` and `null_verbs` options and ran into an error. Here's the traceback:

```
Traceback (most recent call last):
  File "tests/test_petrarch.py", line 147, in <module>
    test_petr_formatted_to_results()
  File "tests/test_petrarch.py", line 142, in test_petr_formatted_to_results
    parsed=True)
  File "/Users/ahalterman/MIT/NSF_RIDIR/UniversalPetrarch/UniversalPetrarch/petrarch_ud.py", line 428, in run_pipeline
    read_dictionaries()
  File "/Users/ahalterman/MIT/NSF_RIDIR/UniversalPetrarch/UniversalPetrarch/petrarch_ud.py", line 158, in read_dictionaries
    PETRreader.read_actor_dictionary(actor_path)
  File "/Users/ahalterman/MIT/NSF_RIDIR/UniversalPetrarch/UniversalPetrarch/PETRreader.py", line 1989, in read_actor_dictionary
    actordict["#"].extend(check_date_boundaries(datelist))
  File "/Users/ahalterman/MIT/NSF_RIDIR/UniversalPetrarch/UniversalPetrarch/PETRreader.py", line 1901, in check_date_boundaries
    if not item[1]: #actor code without time restriction
IndexError: list index out of range
```

I get the error when I run [this file](https://github.com/ahalterman/UniversalPetrarch/blob/master/UniversalPetrarch/tests/test_petrarch.py) in my fork of UniversalPetrarch.

Here's the config file I'm using:
[PETR_config.txt](https://github.com/openeventdata/UniversalPetrarch/files/1734801/PETR_config.txt)

**Comment by JingL1014** [comment]
i added the run_pipeline() in the petrarch_ud.py. I didn't run in errors when running the file in your fork. But i still need to implement the functions with null_actors and null_verbs options in UDpetrarch as in petrarch2.
