### ISSUE TITLE
python3 basestring issue 

### ISSUE THREAD

**Issue by khaledJabr** [openeventdata/UniversalPetrarch#41]
When running UP python3 version, I encounter this after UP is done coding events 

```
Summary:
Stories read: 4    Sentences coded: 5   Events generated: 15
Discards:  Sentence 0   Story 0   Sentences without events: 3
Average Coding time =  0.0825836181640625
Traceback (most recent call last):
  File "petrarch_ud.py", line 495, in <module>
    main()
  File "petrarch_ud.py", line 81, in main
    run(paths, out , True)  ## <===
  File "petrarch_ud.py", line 452, in run
    PETRwriter.write_events(updated_events, 'evts.' + out_file)
  File "/Users/kld/Documents/workspace/EventData/UniversalPetrarch/UniversalPetrarch/PETRwriter.py", line 74, in write_events
    if not isinstance(event[3], basestring): # occasional issue in PETR-2 due to mishandling of multi-word verb PAS 15.04.03, modified 18.06.01
NameError: name 'basestring' is not defined

```

I commented out  [the line firing the error](https://github.com/openeventdata/UniversalPetrarch/blob/ad8f636d2f76d5c116e9eef21774c2e66bf5a2f1/UniversalPetrarch/python3/PETRwriter.py#L74), and it seemed to go through, however, I did not face this issue when I was using python2 version, and I don't want to be omitting some side functionality.

**Comment by JingL1014** [comment]
I fixed the error. In python3, it should be "str" not "basestring".
