### ISSUE TITLE
UP Arabic synset issue 

### ISSUE THREAD

**Issue by khaledJabr** [openeventdata/UniversalPetrarch#42]
Here is an issue that I have run into recently with UP Arabic. The issue is that for some certain sentences with certain sysets, UP break. I am suspecting it is failing to match the sysnset at some point, but not quite sure why. Here is an example sentence that does it 

```
<Sentence date="2011021" id="e6874d82b9c4d0103fd007efea0e7eca336dea0efc24441a27868905f8f508400568a4339b405423780fc901f4b44ac874cabdd4847a129bd52c487236b7702eb2839901884764120dd376dba6b3ce8f0fad1eaefe94289b26a3a99547bb73c1ceec524348646713219eeeb3183be619e7bfed1e1a71f7bcd3e2a66051959b20af90e0ebef2f9fa3_4" sentence="false" source="An-Nahar (Arabic)"><Text>وتفيد المعلومات اياها ثالثاً ان الادارة الاميركية وضعت الرئيس المكلف مباشرة ورسمياً، وكذلك من خلال اتصالات غير مباشرة جرت بينها وبينه بواسطة قريبين منه، في اجواء "الخطوط الحمر" التي يفترض فيه ان لا يتجاوزها سواء اثناء تأليفه الحكومة او بعد مباشرتها العمل الفعلي في اعقاب نيلها الثقة.</Text><Parse>1	و	و	CCONJ	C---------	_	0	root	_	_
2	تفيد	أفاد	VERB	VIIA-3FS--	Aspect=Imp|Gender=Fem|Mood=Ind|Number=Sing|Person=3|VerbForm=Fin|Voice=Act	1	parataxis	_	_
3	المعلومات	معلومة	NOUN	N------P1D	Case=Nom|Definite=Def|Number=Plur	2	nsubj	_	_
4	ايا	أي	ADJ	A-----MS4I	Case=Acc|Definite=Ind|Gender=Masc|Number=Sing	5	amod	_	_
5	ها	هو	PRON	SP---3FS2-	Case=Gen|Gender=Fem|Number=Sing|Person=3|PronType=Prs	3	nmod	_	_
6	ثالثا	ثالث	ADJ	A-----MS4I	Case=Acc|Definite=Ind|Gender=Masc|Number=Sing	2	obl	_	_
7	ان	أن	CCONJ	C---------	_	10	mark	_	_
8	الادارة	إدارة	NOUN	N------S4D	Case=Acc|Definite=Def|Number=Sing	10	nsubj	_	_
9	الاميركية	أميركي	ADJ	A-----FS4D	Case=Acc|Definite=Def|Gender=Fem|Number=Sing	8	amod	_	_
10	وضعت	وضع	VERB	VP-A-3FS--	Aspect=Perf|Gender=Fem|Number=Sing|Person=3|Voice=Act	6	ccomp	_	_
11	الرئيس	رئيس	NOUN	N------S1D	Case=Nom|Definite=Def|Number=Sing	10	obj	_	_
12	المكلف	مكلف	ADJ	A-----MS1D	Case=Nom|Definite=Def|Gender=Masc|Number=Sing	11	amod	_	_
13	مباشرة	مباشر	NOUN	N------S4I	Case=Acc|Definite=Ind|Number=Sing	11	nmod	_	_
14	و	و	CCONJ	C---------	_	15	cc	_	_
15	رسميا	رسمي	ADJ	A-----MS4I	Case=Acc|Definite=Ind|Gender=Masc|Number=Sing	13	conj	_	_
16	,	,	PUNCT	G---------	_	15	punct	_	_
17	و	و	CCONJ	C---------	_	19	cc	_	_
18	ك	ك	ADP	P---------	AdpType=Prep	19	case	_	_
19	ذلك	ذٰلك	PRON	SD----MS2-	Case=Gen|Gender=Masc|Number=Sing|PronType=Dem	12	conj	_	_
20	من	من	ADP	P---------	AdpType=Prep	22	case	_	_
21	خلال	خلال	ADP	PI------2-	AdpType=Prep|Case=Gen	22	case	_	_
22	اتصالات	اتصال	NOUN	N------P2I	Case=Gen|Definite=Ind|Number=Plur	19	nmod	_	_
23	غير	غير	NOUN	N------S2R	Case=Gen|Definite=Cons|Number=Sing	22	nmod	_	_
24	مباشرة	مباشر	ADJ	A-----FS2I	Case=Gen|Definite=Ind|Gender=Fem|Number=Sing	23	amod	_	_
25	جرت	جرى	VERB	VP-A-3FS--	Aspect=Perf|Gender=Fem|Number=Sing|Person=3|Voice=Act	19	acl	_	_
26	بين	بين	ADP	PI------4-	AdpType=Prep|Case=Acc	27	case	_	_
27	ها	هو	PRON	SP---3FS2-	Case=Gen|Gender=Fem|Number=Sing|Person=3|PronType=Prs	25	obj	_	_
28	و	و	CCONJ	C---------	_	30	cc	_	_
29	بين	بين	ADP	PI------4-	AdpType=Prep|Case=Acc	30	case	_	_
30	ه	هو	PRON	SP---3MS2-	Case=Gen|Gender=Masc|Number=Sing|Person=3|PronType=Prs	27	conj	_	_
31	ب	ب	ADP	P---------	AdpType=Prep	32	case	_	_
32	واسطة	واسطة	NOUN	N------S2R	Case=Gen|Definite=Cons|Number=Sing	25	obl	_	_
33	قريبين	بقرين	ADJ	A-----MP2I	Case=Gen|Definite=Ind|Gender=Masc|Number=Plur	32	amod	_	_
34	من	من	ADP	P---------	AdpType=Prep	35	case	_	_
35	ه	هو	PRON	SP---3MS2-	Case=Gen|Gender=Masc|Number=Sing|Person=3|PronType=Prs	33	nmod	_	_
36	,	,	PUNCT	G---------	_	35	punct	_	_
37	في	في	ADP	P---------	AdpType=Prep	38	case	_	_
38	اجواء	جو	NOUN	N------P2R	Case=Gen|Definite=Cons|Number=Plur	32	nmod	_	_
39	"	"	PUNCT	G---------	_	40	punct	_	_
40	الخطوط	خط	NOUN	N------P2D	Case=Gen|Definite=Def|Number=Plur	38	nmod	_	_
41	الحمر	أحمر	ADJ	A-----MP2D	Case=Gen|Definite=Def|Gender=Masc|Number=Plur	40	amod	_	_
42	"	"	PUNCT	G---------	_	40	punct	_	_
43	التي	الذي	DET	SR----FS2-	Case=Gen|Gender=Fem|Number=Sing|PronType=Rel	38	cc	_	_
44	يفترض	افترض	VERB	VIIP-3MS--	Aspect=Imp|Gender=Masc|Mood=Ind|Number=Sing|Person=3|VerbForm=Fin|Voice=Pass	38	acl	_	_
45	في	في	ADP	P---------	AdpType=Prep	46	case	_	_
46	ه	هو	PRON	SP---3MS2-	Case=Gen|Gender=Masc|Number=Sing|Person=3|PronType=Prs	44	obl	_	_
47	ان	أن	CCONJ	C---------	_	49	mark	_	_
48	لا	لا	PART	F---------	_	49	advmod	_	_
49	يتجاوز	تجاوز	VERB	VIIA-3MS--	Aspect=Imp|Gender=Masc|Mood=Ind|Number=Sing|Person=3|VerbForm=Fin|Voice=Act	44	csubj	_	_
50	ها	هو	PRON	SP---3FS4-	Case=Acc|Gender=Fem|Number=Sing|Person=3|PronType=Prs	49	obj	_	_
51	سواء	سواء	NOUN	N------S4I	Case=Acc|Definite=Ind|Number=Sing	53	cc	_	_
52	اثناء	أثناء	ADP	PI------4-	AdpType=Prep|Case=Acc	53	case	_	_
53	تاليف	تأليف	NOUN	N------S2R	Case=Gen|Definite=Cons|Number=Sing	49	obl	_	_
54	ه	هو	PRON	SP---3MS2-	Case=Gen|Gender=Masc|Number=Sing|Person=3|PronType=Prs	53	nmod	_	_
55	الحكومة	حكومة	NOUN	N------S1D	Case=Nom|Definite=Def|Number=Sing	53	nmod	_	_
56	او	أو	CCONJ	C---------	_	58	cc	_	_
57	بعد	بعد	ADP	PI------4-	AdpType=Prep|Case=Acc	58	case	_	_
58	مباشرت	مباشرت	NOUN	N------P2R	Case=Gen|Definite=Cons|Number=Plur	53	conj	_	_
59	ها	هو	PRON	SP---3FS2-	Case=Gen|Gender=Fem|Number=Sing|Person=3|PronType=Prs	58	nmod	_	_
60	العمل	عمل	NOUN	N------S1D	Case=Nom|Definite=Def|Number=Sing	58	nmod	_	_
61	الفعلي	فعلي	ADJ	A-----MS1D	Case=Nom|Definite=Def|Gender=Masc|Number=Sing	60	amod	_	_
62	في	في	ADP	P---------	AdpType=Prep	63	case	_	_
63	اعقاب	عقب	NOUN	N------P2R	Case=Gen|Definite=Cons|Number=Plur	60	nmod	_	_
64	نيل	نيل	NOUN	N------S2R	Case=Gen|Definite=Cons|Number=Sing	63	nmod	_	_
65	ها	هو	PRON	SP---3FS2-	Case=Gen|Gender=Fem|Number=Sing|Person=3|PronType=Prs	64	nmod	_	_
66	الثقة	ثقة	NOUN	N------S1D	Case=Nom|Definite=Def|Number=Sing	65	nsubj	_	_
67	.	.	PUNCT	G---------	_	1	punct	_	_
</Parse></Sentence>

```

And here is the output error

```
Traceback (most recent call last):
  File "petrarch_ud.py", line 495, in <module>
    main()
  File "petrarch_ud.py", line 81, in main
    run(paths, out , True)  ## <===
  File "petrarch_ud.py", line 450, in run
    updated_events = do_coding(events)
  File "petrarch_ud.py", line 342, in do_coding
    p2_coded_events = sentence.get_events()
  File "/Users/kld/Documents/workspace/EventData/UniversalPetrarch/UniversalPetrarch/PETRgraph.py", line 2045, in get_events
    self.get_verb_code()
  File "/Users/kld/Documents/workspace/EventData/UniversalPetrarch/UniversalPetrarch/PETRgraph.py", line 1277, in get_verb_code
    verbcode, matched, meanings, tripleID, triple_dict = self.get_verb_code_per_triplet(triple)
  File "/Users/kld/Documents/workspace/EventData/UniversalPetrarch/UniversalPetrarch/PETRgraph.py", line 1833, in get_verb_code_per_triplet
    lowermatch = match_lower(patternDictPath, verb, target)
  File "/Users/kld/Documents/workspace/EventData/UniversalPetrarch/UniversalPetrarch/PETRgraph.py", line 1684, in match_lower
    temptargetmatch,_ = match_noun(path, np)
  File "/Users/kld/Documents/workspace/EventData/UniversalPetrarch/UniversalPetrarch/PETRgraph.py", line 1411, in match_noun
    match = reroute1(subpath,lambda a: match_noun(a, pp_np), matchphrase, matchphrase)
  File "/Users/kld/Documents/workspace/EventData/UniversalPetrarch/UniversalPetrarch/PETRgraph.py", line 1570, in reroute1
    match = o1(subpath['-'])
  File "/Users/kld/Documents/workspace/EventData/UniversalPetrarch/UniversalPetrarch/PETRgraph.py", line 1411, in <lambda>
    match = reroute1(subpath,lambda a: match_noun(a, pp_np), matchphrase, matchphrase)
  File "/Users/kld/Documents/workspace/EventData/UniversalPetrarch/UniversalPetrarch/PETRgraph.py", line 1444, in match_noun
    a, noun_phrase)) if isinstance(noun_phrase, NounPhrase) else None,lambda a: False,lambda a: False)
  File "/Users/kld/Documents/workspace/EventData/UniversalPetrarch/UniversalPetrarch/PETRgraph.py", line 1529, in reroute
    match = reroute(subpath[','], True,lambda a: False,lambda a: False,lambda a: False, 1)
  File "/Users/kld/Documents/workspace/EventData/UniversalPetrarch/UniversalPetrarch/PETRgraph.py", line 1513, in reroute
    match = o1(subpath['-'])
TypeError: 'bool' object is not callable
```

You can reproduce the error by running the code in `arabic` branch.

**Comment by JingL1014** [comment]
I found in the Arabic verb dictionary there is a small format issue in [line 5867](https://github.com/openeventdata/UniversalPetrarch/blob/d5586c53fa4b2facd02fbfe189c37baaae639270/UniversalPetrarch/data/dictionaries/arabic/CAMEO.ar.0.2.txt#L5867). The correct one should add "{}" around the noun phrase. For line 5867, it should be "- * (ب {واسطة &AIRCRAFT})   [195]  # قصف". After fixing this, the code will not generate errors.

**Comment by khaledJabr** [comment]
It worked. This helped solve many other similar issues too!
