### ISSUE TITLE
Error on PETR.UnitTest

### ISSUE THREAD

**Issue by ahalterman** [openeventdata/UniversalPetrarch#9]
I get an error when running on the UnitTest using the parsed document that comes with the repo. When I run

```
python2 petrarch_ud.py batch -i data/text/PETR.UnitTest.records.parsing_parsed_udpipe_2.0.xml -o output.txt
```

I get this error:

```
Traceback (most recent call last):
  File "petrarch_ud.py", line 409, in <module>
    main()
  File "petrarch_ud.py", line 71, in main
    run(paths, out , True)  ## <===
  File "petrarch_ud.py", line 402, in run
    events = PETRreader.read_xml_input(filepaths, s_parsed)
  File "/Users/ahalterman/MIT/NSF_RIDIR/UniversalPetrarch/UniversalPetrarch/PETRreader.py", line 2325, in read_xml_input
    holding[entry_id]['sents'][sent_id] = sent_dict
UnboundLocalError: local variable 'sent_id' referenced before assignment
```

**Comment by JingL1014** [comment]
I think the reason is that the format of UnitTest is not compatible with the required format of PETRARCH. I will upload another version of UnitTest with compatible format.

**Comment by PTB-OEDA** [comment]
This needs to be fixed asap so we will be able to test the Spanish and
Arabic....
